import React, { useEffect, useState } from "react";
import { apiGet } from "../api";

export default function CoachReport() {
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadReport() {
      try {
        setLoading(true);
        setError("");

        const data = await apiGet("/coach/report");
        setReport(data.coach_report || "No report available.");
      } catch (err) {
        console.error(err);
        setError("Could not load coach report.");
      } finally {
        setLoading(false);
      }
    }

    loadReport();
  }, []);

  return (
    <div className="p-6 space-y-6 bg-gray-50 min-h-screen">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">AI Coach Report</h1>
        <p className="text-gray-500 mt-1">
          Full tactical report generated by the backend.
        </p>
      </div>

      {loading && <p className="text-gray-600">Loading coach report...</p>}

      {error && (
        <div className="bg-red-100 text-red-700 p-4 rounded-xl">{error}</div>
      )}

      {!loading && !error && (
        <div className="bg-white rounded-2xl shadow p-6 border border-gray-100">
          <pre className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
            {report}
          </pre>
        </div>
      )}
    </div>
  );
}